#设置启动端口80
server:
  port: 8080

#spring的数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-001?serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  #jpa设置为update模式，在执行是显示sql语句在控制台
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

